// Generated by CoffeeScript 1.8.0
(function() {
  Template.googlePlaces.rendered = function() {
    window.onload = function() {
      var autocomplete;
      autocomplete = new google.maps.places.Autocomplete(document.getElementById("autocomplete"), {
        types: ["geocode"]
      });
    };
  };

}).call(this);

//# sourceMappingURL=googlePlaces.js.map
