// Generated by CoffeeScript 1.8.0
(function() {
  GoogleMaps.init;

  ({
    key: "AIzaSyDOmMDcMCO-lB8DYhWEkdB7OJ3WIKadRtg",
    language: "en"
  });

}).call(this);

//# sourceMappingURL=googlePlaces.js.map
